name: tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: Tests ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install testing dependencies
      run: yarn install

    - name: Run Tests
      run: yarn test
