name: tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Shell Mock
      run: |
        git clone https://github.com/capitalone/bash_shell_mock
        cd bash_shell_mock
        sudo ./install.sh /usr/local

    - name: Where is shellmock?
      run: which shellmock

    - name: Install BATS
      run: yarn install

    - name: Run Tests
      run: yarn test

